#!/bin/bash

#BSUB -P CSC314
#BSUB -W 2:00
#BSUB -nnodes 1
#BSUB -alloc_flags gpumps
#BSUB -J vec_ops
#BSUB -o vec_ops.%J

for SIZE in 1000 10000 100000 1000000 10000000 100000000 1000000000
do
	for x in {1..42}
	do
		jsrun -n 2 -c 21 -g 1 -p $x -d cyclic -b packed:2 -o vec_ops.n2_g0_c21_p${x}.${SIZE}.${LSB_JOBID} ~/petsc/src/vec/vec/examples/tests/hannah-vec-ops-permute-operations -n $SIZE -vec_type mpi -log_view
	done
done

